# TF-IDF, n-gram 적용

In [2]:
import pandas as pd

# CSV 파일 불러오기
file_path = './data/HScode(0630)/basic_data_frame.csv'  # 여기에 실제 파일 경로를 입력하세요
df = pd.read_csv(file_path)

In [8]:
df

               id                                      DEC_processed
0       101211000  live horse ass mule hinny horse purebred breed...
1       101219000  live horse ass mule hinny horse purebred breed...
2       101291000       live horse ass mule hinny horse horse racing
3       101299000                    live horse ass mule hinny horse
4       101300000                  live horse ass mule hinny ass ass
...           ...                                                ...
11442  9706102000  antique age exceeding year age exceeding year ...
11443  9706103000  antique age exceeding year age exceeding year ...
11444  9706901000                 antique age exceeding year ceramic
11445  9706902000      antique age exceeding year musical instrument
11446  9706903000                         antique age exceeding year

[11447 rows x 2 columns]

# 각 행의 텍스트를 n-gram을 활용하여 구성하는 단어들을 뽑고, TF-IDF를 활용해 텍스트를 대표할 수 있는 단어들을 숫자로 변환.

In [4]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# 데이터 로드
file_path = './data/HScode(0630)/basic_data_frame.csv'
df = pd.read_csv(file_path)

# Step 1: 'id' 열을 인덱스로 설정
df.set_index('id', inplace=True)

# Step 2: 사용자 정의 토크나이저를 정의하여 최대 2-gram 생성
def custom_tokenizer(text):
    tokens = text.split()
    ngrams = tokens[:]
    for i in range(len(tokens) - 1):
        ngrams.append(tokens[i] + ' ' + tokens[i+1])
    return ngrams

# Step 3: 사용자 정의 토크나이저를 사용하여 TF-IDF로 벡터화
vectorizer = TfidfVectorizer(tokenizer=custom_tokenizer)
tfidf_matrix = vectorizer.fit_transform(df['DEC_processed'])

# Step 4: TF-IDF 행렬을 데이터프레임으로 변환
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), index=df.index, columns=vectorizer.get_feature_names_out())

# 결과 데이터프레임 저장
tfidf_df.to_csv('./data/HScode(0630)/TD_IDF_vectorizing.csv')

# 데이터프레임의 크기 확인
print(tfidf_df.shape)

c:\Users\user\anaconda3\envs\shin\Lib\site-packages\sklearn\feature_extraction\text.py:523: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

(11447, 31663)

In [5]:
tfidf_df

,ab,ab copolymer,abaca,abaca manila,abalone,abalone airtight,abalone haliotis,abalone shell,abies,abies spp,...,zirconium article,zirconium dioxide,zirconium ore,zirconium powder,zirconium silicate,zirconium weight,zizyphi,zizyphi semen,zoological,zoological botanical
id,,,,,,,,,,,,,,,,,,,,,
101211000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101219000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101291000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101299000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101300000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9706102000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9706103000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9706901000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9706902000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9706903000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
import pandas as pd

# 업로드된 파일 로드
df1 = pd.read_csv('./data/HScode(0630)/TF_IDF_vectorizing.csv')
df2 = pd.read_csv('./data/HScode(DSC0630)/dsc_vector_data_frame.csv')

# test2_df의 열을 test_df에 추가
combined_df = pd.concat([df1, df2], axis=0)

# 병합된 데이터프레임을 새로운 Excel 파일로 저장
combined_df.to_csv('./data/HScode(DSC0630)/concat_perfect.csv', index=False)


print(combined_df.head())

            id   ab  ab copolymer  abaca  abaca manila  abalone  \
0  101211000.0  0.0           0.0    0.0           0.0      0.0
1  101219000.0  0.0           0.0    0.0           0.0      0.0
2  101291000.0  0.0           0.0    0.0           0.0      0.0
3  101299000.0  0.0           0.0    0.0           0.0      0.0
4  101300000.0  0.0           0.0    0.0           0.0      0.0

   abalone airtight  abalone haliotis  abalone shell  abies  ...  \
0               0.0               0.0            0.0    0.0  ...
1               0.0               0.0            0.0    0.0  ...
2               0.0               0.0            0.0    0.0  ...
3               0.0               0.0            0.0    0.0  ...
4               0.0               0.0            0.0    0.0  ...

   zirconium article  zirconium dioxide  zirconium ore  zirconium powder  \
0                0.0                0.0            0.0               0.0
1                0.0                0.0            0.0               0.0
2                0.0                0.0            0.0               0.0
3                0.0                0.0            0.0               0.0
4                0.0                0.0            0.0               0.0

   zirconium silicate  zirconium weight  zizyphi  zizyphi semen  zoological  \
0                 0.0               0.0      0.0            0.0         0.0
1                 0.0               0.0      0.0            0.0         0.0
2                 0.0               0.0      0.0            0.0         0.0
3                 0.0               0.0      0.0            0.0         0.0
4                 0.0               0.0      0.0            0.0         0.0

   zoological botanical
0                   0.0
1                   0.0
2                   0.0
3                   0.0
4                   0.0

[5 rows x 31664 columns]

In [1]:
import pandas as pd
df2 = pd.read_csv('./data/HScode(DSC0630)/dsc_vector_data_frame.csv')
df2

,ab,ab copolymer,abaca,abaca manila,abalone,abalone airtight,abalone haliotis,abalone shell,abies,abies spp,...,zirconium article,zirconium dioxide,zirconium ore,zirconium powder,zirconium silicate,zirconium weight,zizyphi,zizyphi semen,zoological,zoological botanical
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
df2

,ab,ab copolymer,abaca,abaca manila,abalone,abalone airtight,abalone haliotis,abalone shell,abies,abies spp,...,zirconium article,zirconium dioxide,zirconium ore,zirconium powder,zirconium silicate,zirconium weight,zizyphi,zizyphi semen,zoological,zoological botanical
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# 데이터 파일 경로 설정
file_path = './data/HScode(DSC0630)/concat_perfect.csv'
# CSV 파일을 읽어서 DataFrame으로 변환
df = pd.read_csv(file_path)
# 'id' 열을 인덱스로 설정
df.set_index('id', inplace=True)

# 행 간의 코사인 유사도 계산
cosine_sim_matrix = cosine_similarity(df)

# 코사인 유사도 행렬을 DataFrame으로 변환하여 가독성 향상
cosine_sim_df = pd.DataFrame(cosine_sim_matrix, index=df.index, columns=df.index)

# 결과를 CSV 파일로 저장
csv_file_path = './data/HScode(DSC0630)/Similarity_TD_IDF.csv'
cosine_sim_df.to_csv(csv_file_path, index=False)

# 코사인 유사도 행렬의 처음 30개 행을 출력
cosine_sim_df.head(30)

id,101211000.0,101219000.0,101291000.0,101299000.0,101300000.0,101900000.0,102211000.0,102212000.0,102219000.0,102291000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id,,,,,,,,,,,,,,,,,,,,,
101211000.0,1.000000,0.876445,0.589684,0.675914,0.487751,0.614714,0.318321,0.324333,0.346476,0.051423,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101219000.0,0.876445,1.000000,0.711313,0.815329,0.588355,0.741506,0.320801,0.326860,0.349175,0.062030,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101291000.0,0.589684,0.711313,1.000000,0.872424,0.597672,0.763518,0.023508,0.023952,0.025587,0.031431,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101299000.0,0.675914,0.815329,0.872424,1.000000,0.721616,0.909455,0.030286,0.030858,0.032965,0.040494,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101300000.0,0.487751,0.588355,0.597672,0.721616,1.000000,0.806029,0.023642,0.024089,0.025733,0.031611,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101900000.0,0.614714,0.741506,0.763518,0.909455,0.806029,1.000000,0.036260,0.036945,0.039468,0.048482,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102211000.0,0.318321,0.320801,0.023508,0.030286,0.023642,0.036260,1.000000,0.860024,0.918740,0.625982,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102212000.0,0.324333,0.326860,0.023952,0.030858,0.024089,0.036945,0.860024,1.000000,0.936091,0.569369,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102219000.0,0.346476,0.349175,0.025587,0.032965,0.025733,0.039468,0.918740,0.936091,1.000000,0.608241,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102291000.0,0.051423,0.062030,0.031431,0.040494,0.031611,0.048482,0.625982,0.569369,0.608241,1.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102292000.0,0.052631,0.063486,0.032169,0.041445,0.032353,0.049621,0.571938,0.617402,0.622525,0.720874,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102299000.0,0.061273,0.073911,0.037451,0.048250,0.037666,0.057769,0.665854,0.678430,0.724747,0.839246,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102310000.0,0.300629,0.302971,0.022201,0.028603,0.022328,0.034245,0.538761,0.548936,0.586413,0.307528,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102391000.0,0.052542,0.063379,0.032114,0.041375,0.032298,0.049536,0.401336,0.338992,0.362136,0.492844,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102392000.0,0.053832,0.064935,0.032903,0.042390,0.033091,0.050753,0.340878,0.382769,0.371028,0.410935,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102399000.0,0.063192,0.076226,0.038624,0.049761,0.038845,0.059577,0.400148,0.407706,0.435540,0.482385,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102901000.0,0.384435,0.387431,0.028390,0.036576,0.028553,0.043792,0.688951,0.701963,0.749888,0.393258,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102909010.0,0.062763,0.075709,0.038362,0.049424,0.038582,0.059174,0.651879,0.404942,0.432588,0.588725,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102909020.0,0.066078,0.079708,0.040388,0.052034,0.040620,0.062299,0.418426,0.634973,0.455435,0.504420,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102909090.0,0.082075,0.099004,0.050166,0.064631,0.050453,0.077381,0.519724,0.529540,0.565693,0.626537,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103100000.0,0.387217,0.385630,0.030308,0.039048,0.030482,0.046750,0.456655,0.465280,0.497046,0.088298,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103910000.0,0.027010,0.032581,0.031017,0.039960,0.031194,0.047843,0.035972,0.036651,0.039153,0.048096,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103920000.0,0.030808,0.037162,0.035378,0.045579,0.035581,0.054571,0.041030,0.041805,0.044659,0.054859,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104101000.0,0.304417,0.303170,0.023827,0.030698,0.023964,0.036754,0.359008,0.365788,0.390761,0.069417,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104109000.0,0.027473,0.033139,0.031548,0.040645,0.031729,0.048663,0.036588,0.037279,0.039824,0.048920,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104201000.0,0.019303,0.023285,0.022167,0.028559,0.022294,0.034193,0.073079,0.026194,0.027982,0.097710,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104209000.0,0.027264,0.032887,0.031308,0.040336,0.031488,0.048293,0.036310,0.036996,0.039522,0.048548,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
105111000.0,0.162123,0.161459,0.012690,0.016349,0.012762,0.019574,0.191196,0.194808,0.208107,0.036970,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
105119000.0,0.011792,0.014224,0.013541,0.017446,0.013619,0.020888,0.015705,0.016001,0.017094,0.020998,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
105120000.0,0.013087,0.015786,0.015028,0.019361,0.015114,0.023181,0.017429,0.017758,0.018970,0.023303,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Company 와 HScode 간 코사인 유사도가 구해진 데이터만 저장

In [4]:
import pandas as pd

csv_file_path = './data/HScode(DSC0630)/Similarity_TD_IDF.csv'

# CSV 파일 읽기
df = pd.read_csv(csv_file_path)

# 첫 행부터 11446행까지 삭제
df = df.drop(index=df.index[:11447])

# 첫 11448열만 남기기
df = df.iloc[:, :11447]

In [5]:
import pandas as pd

# CSV 파일 경로를 실제 경로로 변경
csv_file_path = './data/HScode(DSC0630)/Similarity_TD_IDF_delet.csv'
df.to_csv(csv_file_path)

print("데이터가 'drop_final.csv' 파일로 저장되었습니다.")

데이터가 'drop_final.csv' 파일로 저장되었습니다.

In [6]:
import pandas as pd

# CSV 파일 경로를 실제 경로로 변경
csv_file_path = './data/HScode(DSC0630)/Similarity_TD_IDF_delet.csv'
df = pd.read_csv(csv_file_path)
df

,Unnamed: 0,101211000.0,101219000.0,101291000.0,101299000.0,101300000.0,101900000.0,102211000.0,102212000.0,102219000.0,...,9705220000.0,9705290000.0,9705310000.0,9705390000.0,9706101000.0,9706102000.0,9706103000.0,9706901000.0,9706902000.0,9706903000.0
0,11447,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,11448,0.137026,0.095856,0.0,0.0,0.0,0.0,0.211664,0.215662,0.230385,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,11449,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,11450,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.008222,0.0,0.017504,0.0,0.083976,0.082916,0.085898,0.064637,0.060611,0.073947
4,11451,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.005935,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,21442,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9996,21443,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9997,21444,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.028861,0.000000,0.000000,0.063291,0.000000
9998,21445,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9999,21446,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

# Company 데이터와 HScode 간 유사성이 높을 것으로 판단되는 top 20개 선별

In [ ]:
import pandas as pd

csv_file_path = './data/HScode(DSC0630)/Similarity_TD_IDF_delet.csv'

# CSV 파일 읽기
df_latest = pd.read_csv(csv_file_path)

# 각 행에서 가장 높은 값 열 개의 열 이름을 가져오는 함수 정의
def get_top_ten_columns(row):
    sorted_row = row.sort_values(ascending=False)
    return sorted_row.index[:19].tolist()

# 데이터프레임의 각 행에 함수 적용 (첫 번째 열은 인덱스나 식별자로 보이므로 제외)
top_ten_columns_latest = df_latest.iloc[:, 1:].apply(get_top_ten_columns, axis=1)

# 결과를 더 잘 보기 위해 데이터프레임으로 변환
# 인덱스를 살리기 위해 원본 데이터프레임의 인덱스를 사용
top_ten_columns_df_latest = pd.DataFrame(top_ten_columns_latest.tolist(), 
                                         columns=['Top 1', 'Top 2', 'Top 3', 'Top 4', 'Top 5', 'Top 6', 'Top 7', 'Top 8', 'Top 9', 'Top 10',
                                                  'Top 11', 'Top 12', 'Top 13', 'Top 14', 'Top 15', 'Top 16', 'Top 17', 'Top 18', 'Top 19', 'Top 20'
                                                  ,],
                                         index=df_latest.index)

In [3]:
# Save the resulting DataFrame to an Excel file
output_file_path_latest = './data/HScode(DSC0630)/TD_IDF_20.csv'
top_ten_columns_df_latest.to_csv(output_file_path_latest, index=False)

output_file_path_latest

'./data/lastnight0625(DEC)/TD_IDF_30.csv'

In [4]:
top_ten_columns_df_latest

,Top 1,Top 2,Top 3,Top 4,Top 5,Top 6,Top 7,Top 8,Top 9,Top 10,...,Top 20Top 21,Top 22,Top 23,Top 24,Top 25,Top 26,Top 27,Top 28,Top 29,Top 30
0,8708301000.0,8708302000.0,8708303000.0,8704609090.0,8704909090.0,8704609010.0,8708309000.0,8704601020.0,8704529010.0,8704519010.0,...,8704529090.0,8704909010.0,8604009000.0,8704511020.0,8704521020.0,8704521010.0,8704511010.0,8604004000.0,8704419090.0,8704439090.0
1,106903090.0,106909000.0,511991000.0,511999030.0,511996000.0,511999090.0,511995090.0,511993090.0,511992090.0,102901000.0,...,102909090.0,511911010.0,5102190000.0,511100000.0,511992010.0,511999010.0,511995030.0,102212000.0,106199000.0,106195090.0
2,303899080.0,303891000.0,303895090.0,303893090.0,303899099.0,303896000.0,303821000.0,303822000.0,302899090.0,303898000.0,...,303899020.0,302899020.0,303899040.0,303899060.0,303830000.0,303899093.0,303899030.0,302892000.0,302891000.0,302893000.0
3,8703109000.0,8703102000.0,8703321010.0,8703801000.0,8703337000.0,8703317000.0,8703249010.0,8703401000.0,8703501000.0,8703601000.0,...,8703402000.0,8703249020.0,8703321020.0,8703318000.0,8703900000.0,8703101000.0,8703217000.0,8703241010.0,8703218000.0,8703227000.0
4,7113209000.0,9111901000.0,7113201000.0,7113203000.0,7113202000.0,7115901090.0,7115909090.0,8708991050.0,8708991040.0,8708991010.0,...,8462110000.0,8311909000.0,8311109000.0,8311209000.0,8462199000.0,8462191000.0,8708910000.0,8708930000.0,7115909020.0,8311301000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,8443140000.0,8443150000.0,8443191000.0,8443130000.0,8443160000.0,8443170000.0,8443110000.0,8443199000.0,8443192000.0,8443120000.0,...,8443994010.0,8443313000.0,8443311090.0,8443319000.0,3215110000.0,8443311020.0,8443311030.0,8443311010.0,8442500000.0,8443329000.0
9996,2201100000.0,2202109000.0,2202101000.0,2202999000.0,2202910000.0,2202991000.0,2202992000.0,2202993000.0,2201909000.0,2201901000.0,...,8210002000.0,8438809000.0,8210008000.0,8210005000.0,8438200000.0,8438400000.0,8412902000.0,8402200000.0,8402902000.0,8438509000.0
9997,8419899050.0,8419899010.0,8419899090.0,8419899020.0,8419899030.0,8419899040.0,8419899080.0,8419891000.0,8419899070.0,8419899060.0,...,8419390000.0,9506120000.0,8419509000.0,9010509000.0,8419501000.0,8530101000.0,8419340000.0,8419901000.0,8419400000.0,8419350000.0
9998,7326909000.0,7323940000.0,7326200000.0,7323930000.0,7323910000.0,7323920000.0,7304390000.0,7325993000.0,7323990000.0,7205210000.0,...,7207209000.0,7205290000.0,7204210000.0,7205101000.0,7304900000.0,7201102000.0,7323100000.0,7206900000.0,7205102000.0,9406902000.0
9999,8523802010.0,8523592010.0,8523491010.0,8523499010.0,8523292010.0,8523512010.0,8473303000.0,8473309010.0,8419899050.0,8419899090.0,...,9506110000.0,8419810000.0,8530101000.0,9506120000.0,9506399000.0,9506320000.0,8419909030.0,8530800000.0,9506290000.0,9506391000.0

In [5]:
import pandas as pd

# CSV 파일 경로
csv_file_path = './data/HScode(DSC0630)/TD_IDF_30.csv'

# CSV 파일 읽기
df = pd.read_csv(csv_file_path)

# 랜덤으로 30행 뽑기
random_30_rows = df.sample(n=30, random_state=1)

In [6]:
# Save the resulting DataFrame to an Excel file
output_file_path_latest = './data/HScode(DSC0630)/top30_random_test.csv'
random_30_rows.to_csv(output_file_path_latest, index=False)

output_file_path_latest

'./data/lastnight0625(DEC)/top30_random_test.csv'

In [8]:
import pandas as pd

# 엑셀 파일 경로
file_path = './data/HScode(DSC0630)/modelingverification.xlsx'

# 엑셀 파일의 시트 이름 확인
excel_data = pd.ExcelFile(file_path)
sheet_names = excel_data.sheet_names

# 'iloveyou3' 시트를 데이터프레임으로 불러오기
df = pd.read_excel(file_path)

# HScode와 K_DEC의 매핑을 위한 딕셔너리 생성
hscode_to_kdec = dict(zip(df['HScode'], df['K_DEC']))

# verify_code와 일치하는 HScode를 기반으로 K_DEC 값을 찾는 함수 정의
def find_kdec(verify_code):
    return hscode_to_kdec.get(verify_code, None)

# verify_code 열에 함수를 적용하여 결과를 verify_dec 열에 저장
df['verify_dec'] = df['verify_code'].apply(find_kdec)


# 업데이트된 데이터프레임을 엑셀 파일로 저장
output_file_path = './data/HScode(DSC0630)/modelingverification_updated(최종편집).xlsx'
df.to_excel(output_file_path, index=False)

output_file_path

'./data/lastnight0625(DEC)/modelingverification_updated(최종편집).xlsx'